### ISSUE TITLE
Cant add webhook template via GUI

### ISSUE THREAD

**Issue by wmclendon** [tbotnz/netpalm-admin#13]
Hello,

attempting to add a webhook template for some testing via netpalm-admin GUI, and seems to not work properly (tho very well could be human error).  i navigate to the Rendering Templates -> Webhook templates, and click add, paste in my template in the Template section.  in top right it indicates its adding, no indication of an error, just it does not appear in the list.

in the netpalm-admin logs I see the following when I try to save:

`127.0.0.1 - - [15/Nov/2020 09:27:05] "POST /j2webook/add HTTP/1.1" 404 -` unfortunately no other detail than that.

using the netpalm API endpoint itself `j2template/webhook/` and posting the j2 contents as base64 encoded seems to work fine and then it shows up in the list inside netpalm-admin.

thanks,

Will

**Comment by tbotnz** [comment]
@wmclendon is this fixed now?
